### ISSUE TITLE
Insecure unserialize() usage

### ISSUE THREAD

**Issue by garas** [cardinity/cardinity-whmcs#4]
This WHMCS module unserializes data from user submitted data, which is common vulnerability and might activate some code and compromise WHMCS security.

https://github.com/cardinity/cardinity-whmcs/blob/c75e0364d8a6879083717fd4176984a81646c35d/modules/gateways/cardinity.php#L184

If possible, use JSON format instead. Alternatively add signature to prevent data modification.

**Comment by shababcardinity** [comment]
Applied both recommendation on last patch.
